[package]
name = "powermon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", default-features = false, features = ["derive", "std"] }
thiserror = { version = "1", default-features = false }
